# Generated by Django 4.1.4 on 2023-12-06 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
