# Generated by Django 4.1.4 on 2023-12-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_video_dislikes_video_likes_video_vid_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='video',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='video',
            name='vid_views',
        ),
    ]
